# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tumwebaze
email: ctumwebaze@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my journey working with the android platform. Exploring the it's gems, how certain things are done on it and what you can do with it..
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.tumwebaze.com" # the base hostname & protocol for your site
twitter_username: ctumwebaze
github_username:  ctumwebaze
google_analytics: UA-75143964-1
# Build settings
markdown: kramdown
exclude:
  - docker
  - Gemfile
  - Gemfile.lock
  - Dockerfile